### ISSUE TITLE
Specification Link is Broken

### ISSUE THREAD

**Issue by ungkuhafiz** [oscoin/osrank-rs#89]
Hi. I am new to the project and wants to get started. However, the specification link under the "Getting started" header is broken and not accessible.

`[specification](https://github.com/oscoin/docs/raw/master/osrank/spec/osrank_spec.pdf)`

Thanks.

**Comment by adinapoli-mndc** [comment]
Hey!

Yeah, sorry, you are not the first person complaining about this, but we weren't expecting external interest so soon, and therefore the reason the link is not accessible is because this is part of a private repository within our organisation.

Me and @MeBrei discussed in the past where to host such spec and looks like there is some interest in having this publicly accessible somewhere, so we will make it happen. 😉

**Comment by ungkuhafiz** [comment]
@adinapoli-mndc Thanks!
